### ISSUE TITLE
invalid cross-device link

### ISSUE THREAD

**Issue by kkellner** [pivotal-cf-experimental/stembuild#3]
The tmp directory is expected to be on the same file system as the output directory.   Tried to set the output directory in hopes that it would also use this as the tmp dir, but it did not.   

```
$ ./stembuild -version 1709.2 -vmdk ./Windows2012r2_hw9_stemcell-disk1.vmdk -o ./stemcell -debug 
debug: enabled
debug: using 'ovftool' found at: /usr/bin/ovftool
debug: validating [vmdk] (./Windows2012r2_hw9_stemcell-disk1.vmdk) [vhd] () and [delta] () flags
debug: validating that no extra flags or arguments were provided
debug: validating VMDK file [vmdk]: "./Windows2012r2_hw9_stemcell-disk1.vmdk"
debug: validating output directory: ./stemcell
debug: validating stemcell version string: 1709.2
debug: validating version string: 1709.2
debug: validating OS version: 2012R2
debug: validating that stemcell filename (/home/ECSDENLAB.LOCAL/kkellner/pcf/stemcell/bosh-stemcell-1709.2-vsphere-esxi-windows2012R2-go_agent.tgz) does not exist
debug: created temp directory: /tmp/stemcell-456174914
debug: main: using vmdk (./Windows2012r2_hw9_stemcell-disk1.vmdk)
debug: Creating [image] from [vmdk]: ./Windows2012r2_hw9_stemcell-disk1.vmdk
debug: converting vmx to ova with cmd: /usr/bin/ovftool [/usr/bin/ovftool /tmp/stemcell-456174914/image.vmx /tmp/stemcell-456174914/image.ova]
debug: Sha1 of image (/tmp/stemcell-456174914/image): 35692ad9ebb9a9ada4ea2564e501eef655f9fac5
debug: created temp stemcell.MF file: /tmp/stemcell-456174914/stemcell.MF
debug: wrote stemcell.MF with sha1: 35692ad9ebb9a9ada4ea2564e501eef655f9fac5 and version: 1709.2
debug: creating stemcell
debug: created temp stemcell: /tmp/stemcell-456174914/bosh-stemcell-1709.2-vsphere-esxi-windows2012R2-go_agent.tgz
debug: adding image file to stemcell tarball: /tmp/stemcell-456174914/image
debug: adding file (/tmp/stemcell-456174914/image) to tar archive
debug: adding manifest file to stemcell tarball: /tmp/stemcell-456174914/stemcell.MF
debug: adding file (/tmp/stemcell-456174914/stemcell.MF) to tar archive
debug: created stemcell in: 3m48.591594288s
debug: moving stemcell (/tmp/stemcell-456174914/bosh-stemcell-1709.2-vsphere-esxi-windows2012R2-go_agent.tgz) to: /home/ECSDENLAB.LOCAL/kkellner/pcf/stemcell/bosh-stemcell-1709.2-vsphere-esxi-windows2012R2-go_agent.tgz
Error: rename /tmp/stemcell-456174914/bosh-stemcell-1709.2-vsphere-esxi-windows2012R2-go_agent.tgz /home/ECSDENLAB.LOCAL/kkellner/pcf/stemcell/bosh-stemcell-1709.2-vsphere-esxi-windows2012R2-go_agent.tgz: invalid cross-device link
debug: deleting temp directory: /tmp/stemcell-456174914
```

**Comment by ashwin-venkatesh** [comment]
Hey @kkellner. Have you had a chance to look at [this thread](https://github.com/pivotal-cf-experimental/stembuild/issues/2).

> If this is for Linux, have you tried setting the TMPDIR environment variable while using stembuild? It appears that the code uses os.TempDir("", ... which will default to os.TempDir() which respects the TMPDIR environment variable. https://golang.org/pkg/os/#TempDir

If this is for Windows, it appears that the code uses %WINDIR%\Temp. This may not be flexible enough. I wonder if it would be ok for us to default to the default behavior of os.TempDir for Windows as well which respects the following: first non-empty value from %TMP%, %TEMP%, %USERPROFILE%, or the Windows directory. I see this commit gives an explanation for why os.TempDir may not be acceptable for Windows.

**Comment by kkellner** [comment]
Yes exporting TMPDIR set to point to a director on the same filesystem as the output file does work around the problem.   Long-term it would be good to have a command-line option that specifies a temp directory stembuild uses.

**Comment by ashwin-venkatesh** [comment]
@kkellner Agreed. At this point on time I will put a story into our backlog to make this feature more user-friendly ie make it a command-line option to specify a temp directory. I can't make guarantees about when this will make it into a release but it will get prioritised and picked up by our team eventually.

Here is the story to track progress: https://www.pivotaltracker.com/story/show/155645456

I hope that helps. Would it be fine if I closed this issue?

**Comment by kkellner** [comment]
Great, thanks!   Yes, the issue can be closed.
